"""Procedural level generator.

Levels are generated by rejection sampling: place walls, goals, boxes and
the player at random, then keep the level only if the BFS solver finds a
solution whose length falls inside the requested band. This guarantees
every generated level is solvable and gives direct control over
difficulty via the solution-length band.

The generator is fully determined by the numpy Generator passed in, which
is what makes the hidden-test-set protocol work: freeze this file, agree
on the constraints, and generate the final levels from a secret seed.
"""

from __future__ import annotations

import numpy as np

from latent_sokoban.env import Level
from latent_sokoban.solver import bfs_solve


def generate_level(
    rng: np.random.Generator,
    size: int = 6,
    n_boxes: int = 1,
    wall_density: float = 0.12,
    min_solution_len: int = 2,
    max_solution_len: int = 30,
    max_tries: int = 5000,
) -> tuple[Level, list[int]]:
    """Generate one solvable level. Returns (level, optimal_solution).

    Raises RuntimeError if no valid level is found within max_tries
    (only happens with contradictory constraints).
    """
    for _ in range(max_tries):
        level = _sample_layout(rng, size, n_boxes, wall_density)
        if level is None:
            continue
        solution = bfs_solve(level)
        if solution is None:
            continue
        if min_solution_len <= len(solution) <= max_solution_len:
            return level, solution
    raise RuntimeError(
        f"no solvable level found in {max_tries} tries "
        f"(size={size}, boxes={n_boxes}, band=[{min_solution_len},{max_solution_len}])"
    )


def _sample_layout(
    rng: np.random.Generator, size: int, n_boxes: int, wall_density: float
) -> Level | None:
    walls = np.zeros((size, size), dtype=bool)
    walls[0, :] = walls[-1, :] = walls[:, 0] = walls[:, -1] = True

    interior = [(r, c) for r in range(1, size - 1) for c in range(1, size - 1)]
    n_interior_walls = rng.binomial(len(interior), wall_density)
    idx = rng.choice(len(interior), size=n_interior_walls, replace=False)
    for i in idx:
        walls[interior[i]] = True

    free = [p for p in interior if not walls[p]]
    # boxes need at least one free neighbour on each push axis to ever move,
    # so require boxes to start away from the border ring; goals and the
    # player can be anywhere free.
    if len(free) < 2 * n_boxes + 1:
        return None
    picks = rng.choice(len(free), size=2 * n_boxes + 1, replace=False)
    chosen = [free[i] for i in picks]
    boxes = frozenset(chosen[:n_boxes])
    goals = frozenset(chosen[n_boxes : 2 * n_boxes])
    player = chosen[2 * n_boxes]

    walls_t = tuple(tuple(bool(v) for v in row) for row in walls)
    return Level(walls_t, goals, boxes, player)


def generate_deadlock_level(
    rng: np.random.Generator,
    size: int = 6,
    n_boxes: int = 1,
    wall_density: float = 0.18,
    min_solution_len: int = 4,
    max_solution_len: int = 30,
    max_tries: int = 20000,
) -> tuple[Level, list[int]]:
    """Generate a Split-D level: solvable, but at least one available first
    push leads to an irreversible deadlock. Punishes greedy pushing."""
    from latent_sokoban.env import ACTIONS, SokobanEnv
    from latent_sokoban.solver import state_is_dead

    for _ in range(max_tries):
        level = _sample_layout(rng, size, n_boxes, wall_density)
        if level is None:
            continue
        solution = bfs_solve(level)
        if solution is None or not (min_solution_len <= len(solution) <= max_solution_len):
            continue
        # look for a reachable single push that kills the level
        start = (level.player, level.boxes)
        trap_found = False
        seen = {start}
        frontier = [start]
        # explore only non-pushing moves plus one push
        while frontier and not trap_found:
            key = frontier.pop()
            for action in ACTIONS:
                nxt = SokobanEnv.apply(level, key, action)
                if nxt == key:
                    continue
                if nxt[1] != key[1]:  # this action pushed a box
                    if state_is_dead(level, nxt):
                        trap_found = True
                        break
                elif nxt not in seen:
                    seen.add(nxt)
                    frontier.append(nxt)
        if trap_found:
            return level, solution
    raise RuntimeError("no deadlock-challenge level found; relax constraints")
